generic:
  rewards:
    found: 100.00
    found-all: 250.00
  messages:
    no-console: '&cYou cannot use this command via console.'
    crystal:
      found: '&d&lLOST CRYSTAL FOUND! &eYou have found a &dLost Crystal&e and earned &d$%amount%&e! &6(%found%/%total%)'
      already-found: '&cSorry, but you have already found this lost crystal!'
      found-all: '&d&lLOST CRYSTAL FOUND! &eYou have found &6&lALL &dLost Crystals&e and earned &d$%amount%&e! &6(%found%/%total%)'
commands:
  crystal:
    message: '&eYou have found &d%found%/%total%&e!'
    reloaded: '&aCrystals have been successfully reloaded!'
